apiVersion: batch/v1
kind: CronJob
metadata:
  name: agri-curve-cronjob
  namespace: default
spec:
  schedule: "0 12 * * *"
  timeZone: "America/Sao_Paulo"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      parallelism: 3
      completions: 3
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: agri-curve
            image: nsboan/agri-curve:v2
            env:
            - name: USERNAME
              value: "nsboan"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OUTPUT_DIR
              value: "/output"
            resources:
              requests:
                memory: "2Gi"
                cpu: "1000m"
              limits:
                memory: "2Gi"
                cpu: "2000m"
            volumes:
            - name: output-volume
              hostPath:
                path: /mnt/agri-data
                type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: agri-curve-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: agri-curve
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080