apiVersion: batch/v1
kind: CronJob
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: agri-curve-app:batch/CronJob:default/agri-curve-cronjob
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"batch/v1","kind":"CronJob","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"agri-curve-app:batch/CronJob:default/agri-curve-cronjob"},"name":"agri-curve-cronjob","namespace":"default"},"spec":{"failedJobsHistoryLimit":1,"jobTemplate":{"spec":{"completions":3,"parallelism":3,"template":{"spec":{"containers":[{"env":[{"name":"USERNAME","value":"nsboan"},{"name":"POD_NAME","valueFrom":{"fieldRef":{"fieldPath":"metadata.name"}}},{"name":"OUTPUT_DIR","value":"/output"}],"image":"nsboan/agri-curve:v2","name":"agri-curve","resources":{"limits":{"cpu":"2000m","memory":"2Gi"},"requests":{"cpu":"1000m","memory":"2Gi"}},"volumes":[{"hostPath":{"path":"/mnt/agri-data","type":"Directory"},"name":"output-volume"}]}],"restartPolicy":"OnFailure"}}}},"schedule":"0 12 * * *","successfulJobsHistoryLimit":3,"timeZone":"America/Sao_Paulo"}}
  creationTimestamp: "2025-10-06T23:42:29Z"
  generation: 2
  name: agri-curve-cronjob
  namespace: default
  resourceVersion: "12704"
  uid: 30a1e962-2515-4a63-b470-1e2f01586b2b
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata: {}
    spec:
      completions: 3
      parallelism: 3
      template:
        metadata: {}
        spec:
          containers:
          - env:
            - name: USERNAME
              value: nsboan
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: OUTPUT_DIR
              value: /output
            image: nsboan/agri-curve:v2
            imagePullPolicy: IfNotPresent
            name: agri-curve
            resources:
              limits:
                cpu: "2"
                memory: 2Gi
              requests:
                cpu: "1"
                memory: 2Gi
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
  schedule: 0 12 * * *
  successfulJobsHistoryLimit: 3
  suspend: false
  timeZone: America/Sao_Paulo
status:
  lastSuccessfulTime: "2025-10-06T23:45:50Z"
